# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: vue.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_frontend:

    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: 
        node-version: 12
    - run: npm ci
      working-directory: ${{env.working-directory}}
      
    - name: frontend working
      run: npm run build
      working-directory: ${{env.working-directory}}
    - name: frontend test
      run: npm run test:unit
      working-directory: ${{env.working-directory}}
    
      
